= Notes on my Bluehost VPS account and server
:toc:
:toclevels: 4
:sectnums:
:sectnumlevels: 4

== WHM

Go to https://162.240.31.110:2087/ -- Then log on with username: root
- Password: xxxx


== cPanel

Log on at `bluehost.com`.
Click on "Advanced" or on "cPanel" near the bottom.


== Sudo and root access.

Instead of using `sudo`, I can log on through `ssh` with user name "root".


== Email

To access my email, use:

- URL: https://davekuhlman.org:2096/
- Username: dkuhlman@davekuhlman.org
- Password: xxxx

Enabling inline HTML display in messge view -- Edit file:
`/usr/local/cpanel/base/horde/imp/config/mime_drivers.php`.
Change `'inline' => false,` to `'inline' => true,`.
Search for "gdk".


== Secure shell

Use `~/bin/davekuhlman-ssh.sh`:

----
#!/bin/bash
#ssh davekuhl@davekuhlman.org
ssh dqlvrpmy@davekuhlman.org
----


== FTP

Use `~/bin/davekuhlman-ftp.sh`:

----
# ~/bin/davekuhlman-ftp.sh

#!/bin/bash
lftp davekuhlman.org
----

See `~/.netrc`:

----
# ~/.netrc

machine davekuhlman.org
login dqlvrpmy
password xxxx

machine ftp.reifyonline.org
login reifyonl
password xxxx
----

== Package management, system updates, etc.

View the CentOS release/version in these files:

- `/etc/centos-release`
- `/etc/centos-release-upstream`

Package management is done with `rpm` and/or `yum`.

Help on `yum` and `rpm` is here:
https://www.redhat.com/sysadmin/how-manage-packages

To update all packages to their latest versions, do:

----
$ yum check-update 
$ sudo yum update 
----

To search for packages by keyword, do:

----
$ yum search xxxx
----

To install a package, do:

----
$ sudo yum install xxxx
----

To find out if a package is installed, do:

----
$ rpm -q xxxx
----

To get information about a package, do:

----
$ yum info xxxx
----


== Building and installing Python

See the notes at
`{davekuhlman.org}/home/dqlvrpmy/Python/Python-3.10.0/Notes.adoc0`


