= Lua notes
:toc: left
:sectnums:
:toclevels: 4
:toc-title: Contents:
:stylesheet: dave01.css
:docinfo: shared
:nofooter:


== Data types

=== Strings

Short literal string -- Single or double quotes.  Escape sequences
are interpreted.

Long literal string -- Long brackets.  May run for multiple lines.
Escape sequences are *not* interpreted.  Examples:

- `[[a simple string]]` -- Long bracket level 0.
- `[=[a simple string]=]` -- Long bracket level 1.
- `[==[a simple string]==]` -- Long bracket level 2.


=== Tables and sequences

Some expressions return a sequence that is *not* a table, for
example: (1) `varargs` (`...`) inside a function definition and (2)
`utf8.codepoint(s)`.  We can turn that sequence into a table by
surrounding the expression with brackets, for example `{...}`.

To get the number of items in a sequence, use `select("#", ...)`.

For more hints and clues on this topic see:
https://github.com/moteus/lua-vararg.

== Miscellaneous topics

=== Symbolic links, alternatives

On Ubuntu, the correct symbolic links to the Lua executables were not set up for the
interpreter and compiler.  I found this workaround.

----------
sudo update-alternatives --install /usr/bin/lua lua-interpreter \
/usr/bin/lua5.3 130 --slave /usr/share/man/man1/lua.1.gz \
lua-manual /usr/share/man/man1/lua5.3.1.gz

sudo update-alternatives --install /usr/bin/luac lua-compiler \
/usr/bin/luac5.3 130 --slave /usr/share/man/man1/luac.1.gz \
lua-compiler-manual /usr/share/man/man1/luac5.3.1.gz
----------

See: https://askubuntu.com/questions/850317/installing-lua5-2-vs-lua5-3-on-ubuntu-16-10

=== Reloading a module while in the interactive console

Do this:

----------
> package.loaded.mymodule = nil
> mymodule = require("mymodule")
----------


=== Getting access to the command line arguments

The command line arguments are in global variable `args`.

There is also a module `argparse` at `luarocks`.  Here is an example:

----------
#!/usr/bin/env lua

local argparse = require('argparse')
local transformlib = require('transformlib')

local function main()
    local parser = argparse("script", "convert asciidoc to html")
    parser:argument("inputfilenames", "Input file names")
        :args("+")
    local args = parser:parse()
    transformlib.convert(args.inputfilenames)
end

main()
----------

=== Global variables

See `_ENV` and `_G` variables.  -- But, I do not know what the difference
is between them.

// vim:ft=asciidoc:
