= Notes on my Bluehost VPS account and server
:toc:
:toclevels: 4
:sectnums:
:sectnumlevels: 4

== Pelican Web site archive

I've downloaded that Zip archive in `~/public_html/source/Save` to
`{jackdaw}~/a1/Davekuhlman-org/Save`.


== WHM

Go to:

- https://162.240.31.110:2087/ or

- https://davekuhlman.org:2087/

Then log on with Username: root  Password: xxxx


== cPanel

Log on at `bluehost.com`.
Click on "Advanced" or on "cPanel" near the bottom.


== Sudo and root access.

Instead of using `sudo`, I can log on through `ssh` with user name "root".


== Email

To access my email, use:

- URL: https://davekuhlman.org:2096/
- Username: dkuhlman@davekuhlman.org
- Password: xxxx

Horde -- Enabling inline HTML display in messge view -- Edit file:
`/usr/local/cpanel/base/horde/imp/config/mime_drivers.php`. Change
`'inline' => false,` to `'inline' => true,`. Search for "gdk".


== Secure shell

Use `~/bin/davekuhlman-ssh.sh`:

----
#!/bin/bash
#ssh davekuhl@davekuhlman.org
ssh dqlvrpmy@davekuhlman.org
----


== FTP

Use `~/bin/davekuhlman-ftp.sh`:

----
# ~/bin/davekuhlman-ftp.sh

#!/bin/bash
lftp davekuhlman.org
----

See `~/.netrc`:

----
# ~/.netrc

machine davekuhlman.org
login dqlvrpmy
password xxxx

machine ftp.reifyonline.org
login reifyonl
password xxxx
----

== Package management, system updates, yum, rpm, etc.

View the CentOS release/version in these files:

- `/etc/centos-release`
- `/etc/centos-release-upstream`

Updating software/packages on the server -- In WHM, I did:

- `Software --> Update Server Software`

- `Software --> System update`

- `System Reboot --> Graceful Server Reboot [Documentation]`

Package management can be done with `rpm` and/or `yum`.

Help on `yum` and `rpm` is here:

- https://www.redhat.com/sysadmin/how-manage-packages

- https://www.thegeeksearch.com/how-to-install-and-update-software-packages-using-the-yum-command/

To update all packages to their latest versions, do:

----
$ yum check-update 
$ sudo yum update 
----

Possibly a better way to update all packages -- In a Web browser, go
to WHM -- https://davekuhlman.org:2087/
Then, do:

1. Update Server Software
2. System Update
3. (optionally) System Reboot --> Graceful Server Reboot

To search for packages by keyword, do:

----
$ yum search xxxx
----

To install a package, do:

----
$ sudo yum install xxxx
----

To find out if a package is installed, do:

----
$ rpm -q xxxx
----

To get information about a package, do:

----
$ yum info xxxx
----

To find out which package contains/provides a file, do:

----
$ yum provides /path/to/the/file
----

To clean/clear package cache and more, see `man yum`, and do:

----
$ sudo yum clean all
----


== Building and installing Python

See the notes at
`{davekuhlman.org}/home/dqlvrpmy/Python/Python-3.10.0/Notes.adoc0`


== Upgraded VPS account/plan

I upgraded, on 11/2/2021, from the Standard Bluehost VPS account to
an Enhanced Bluehost VPS account.  It means more money, but also
more (disk/SSD) storage.

Bluehost did the migration for me.  It happened quickly and without
any work by me.
